### ISSUE TITLE
request : find all addresses with value

### ISSUE THREAD

**Issue by ghost** [AdamValach/java-iota-workshop#1]
how to find all addresses with value  trough  java api?

would be  a nice tool to calculate distribution of coins 

thanks

**Comment by AdamValach** [comment]
By all addresses you mean the balance of every non-empty address on the network (totaling 2 779 530 283 MIOTA)?

If so, I am not sure if it should be part of this repository since it seems being much more difficult.

EDIT: But in case you are not a detailist, you can check the statistics at https://thetangle.org/statistics/tokens-distribution

**Comment by ghost** [comment]
yes all addresses with value.  

maybe it's to difficult for this "course" indeed. 

i'm already pulling data from thetangle.org but it's too "wide" info :)
